blank_issues_enabled: true
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/willbarksdale/v/discussions
    about: Ask questions, share ideas, or discuss the project
  - name: 📚 Documentation
    url: https://github.com/willbarksdale/v/blob/main/README.md
    about: Check the README for setup instructions and current features
  - name: 🤝 Contributing Guide
    url: https://github.com/willbarksdale/v/blob/main/CONTRIBUTING.md
    about: Learn how to contribute to the project 