name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem would this feature solve? What's the current pain point?
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see implemented
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature to you?
      options:
        - "🔥 High - This would significantly improve my workflow"
        - "🟡 Medium - This would be nice to have"
        - "🔵 Low - This is just an idea"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which area of the app does this relate to?
      options:
        - "🔐 SSH Connection & Authentication"
        - "📝 File Management & Code Editor"
        - "💻 Terminal & Command Line"
        - "🌐 Preview & WebView"
        - "🎨 User Interface & Experience"
        - "⚡ Performance & Optimization"
        - "🤖 AI Integration (Future)"
        - "🔧 Developer Tools & Utilities"
        - "📱 Mobile-Specific Features"
        - "🌊 Other / Cross-cutting"
    validations:
      required: true

  - type: textarea
    id: mobile-considerations
    attributes:
      label: Mobile Considerations
      description: How should this work on mobile? Any touch interface considerations?
      placeholder: "For mobile devices, this feature should..."
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "I've also thought about..."
    validations:
      required: false

  - type: textarea
    id: examples
    attributes:
      label: Examples or References
      description: Any examples from other apps or tools that implement similar features?
      placeholder: "Similar to how VS Code does X, or like the Y feature in Z app..."
    validations:
      required: false

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation Interest
      description: Are you interested in helping implement this feature?
      options:
        - label: "🙋‍♀️ I'd be interested in working on this feature"
        - label: "💬 I'd like to discuss the technical approach"
        - label: "🧪 I'd be willing to test this feature"
        - label: "📖 I could help with documentation"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or details about the feature request?
    validations:
      required: false 